src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Household_Greeting__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) || ( MailingStreet = &quot;&quot; &amp;&amp; MailingCity = &quot;&quot; &amp;&amp; MailingState = &quot;&quot; ), HouseholdGreeting__c , FirstName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Address Household Greeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Household_Name__c</fullName>
        <description>Equals Household Name if effective primary address is Home</description>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) || ( MailingStreet = &quot;&quot; &amp;&amp; MailingCity = &quot;&quot; &amp;&amp; MailingState = &quot;&quot; ),  HouseholdName__c  , TRIM(FirstName &amp; &quot; &quot; &amp; LastName))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Address Household Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Name_Block_HH__c</fullName>
        <formula>IF ( OR( ISPICKVAL(Primary_Address__c ,&quot;Work&quot;), AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) ) , Primary_Address_Name_Block__c , HouseholdName__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Address Name Block HH</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Org_Name__c</fullName>
        <description>Equal to the account name if and only if there is an account, and the effective primary address is Work.  (11/17/08 MMS)</description>
        <formula>IF ( OR( Account.Name = &quot;Individual&quot; , ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) ) , &quot;&quot; ,
IF ( OR( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) ,  ISPICKVAL( Primary_Address__c, &quot;Work&quot; ) ), Account.Name , &quot;&quot; )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Address Org Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Title__c</fullName>
        <description>Equals title if and only if effective primary address is Work</description>
        <formula>IF ( Account.Name = &quot;Individual&quot; , &quot;&quot; , 
IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; , 
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) ,  Title  , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , &quot;&quot; , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , &quot;&quot; , Title   ) ) ) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Address Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; ,
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) , MailingCity , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , OtherCity , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , OtherCity, MailingCity ) ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Primary mailing City</inlineHelpText>
        <label>Primary City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; , 
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) , MailingCountry , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , OtherCountry , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , OtherCountry , MailingCountry ) ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Primary Country</inlineHelpText>
        <label>Primary Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; ,
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) , MailingPostalCode , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , OtherPostalCode , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , OtherPostalCode , MailingPostalCode ) ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Primary Zip/Postal Code</inlineHelpText>
        <label>Primary Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_State_Province__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; ,
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) , MailingState , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , OtherState , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , OtherState , MailingState ) ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Primary mailing State</inlineHelpText>
        <label>Primary State/Province</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Street__c</fullName>
        <formula>IF ( ISPICKVAL ( Primary_Address__c, &quot;No Mail&quot; ) , &quot;&quot; ,
IF ( AND ( OtherStreet = &quot;&quot; , OtherCity = &quot;&quot; , OtherState = &quot;&quot; ) , MailingStreet , IF ( AND ( MailingStreet = &quot;&quot; , MailingCity = &quot;&quot; , MailingState = &quot;&quot; ) , OtherStreet , IF ( ISPICKVAL ( Primary_Address__c, &quot;Home&quot; ) , OtherStreet, MailingStreet ) ) )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Primary Street Address</inlineHelpText>
        <label>Primary Street</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ONEN_EXT_OppListExport.cls
public class ONEN_EXT_OppListExport {
// Written by Matthew Scholtz, copyright (c) 2009 Groundwire
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

	public List<Opportunity> selectedOpps;
	public List<OpportunityContactRole> finalOpps;
	
	
	public string testreturl {get;set;}
	map<string,string> testparams = new map<string,string>(); 

	public ONEN_EXT_OppListExport(ApexPages.StandardSetController controller) {
      	this.selectedOpps = (List<Opportunity>)controller.getSelected();
      	queryOpps();
      	/*
      	// filterId = '00B80000006diAZ';
      	controller.setFilterId('00B80000006diAZ');
      	this.testreturl = System.currentPageReference().getParameters().get('retURL');
      	*/
      	
      	
      	this.testparams = System.currentPageReference().getParameters();
      	system.debug ('testparams:' + testparams);
      	
      	system.debug ('selectedOpps' + selectedOpps);
	}
	
	private void queryOpps() {
		// tbd make this dynamic apex w/ list of fields in list custom setting??
		finalOpps = [SELECT Contact.FirstName,Contact.LastName,Contact.Primary_Address_Household_Name__c,Contact.Primary_Address_Household_Greeting__c,
			Contact.Primary_Address_Name_Block_HH__c,Contact.Primary_Street__c,Contact.Primary_City__c,Contact.Primary_State_Province__c,
			Contact.Primary_Postal_Code__c,Contact.Primary_Country__c,Contact.Primary_Address_Org_Name__c,Contact.Primary_Address_Title__c,
			Opportunity.Amount,Opportunity.CloseDate,Opportunity.RecordType.Name
			FROM OpportunityContactRole WHERE Opportunity.Id IN :selectedOpps AND IsPrimary=True];
	} 
	
	public list<OpportunityContactRole> getSelectedOpps() {
		return finalOpps;
	}
	
	static testmethod void testNada () {		
		ApexPages.StandardSetController sc = new ApexPages.StandardSetController(
			Database.getQueryLocator([SELECT id FROM Opportunity limit 1]));
		ONEN_EXT_OppListExport ext = new ONEN_EXT_OppListExport(sc); 

	}
	
}