src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Engagement_Level_Numeric__c</fullName>
        <description>set automatically by batch process</description>
        <label>Engagement Level Numeric</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Level__c</fullName>
        <description>set by batch process</description>
        <inlineHelpText>Current engagement level, automatically calculated.  If you want to manually change the level, do not attempt to change this field.  Instead, enter a value in Engagement Level Override.</inlineHelpText>
        <label>Engagement Level</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Observing</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Following</fullName>
                <color>#996633</color>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Endorsing</fullName>
                <color>#66CCCC</color>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Contributing</fullName>
                <color>#9999FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Owning</fullName>
                <color>#663366</color>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Leading</fullName>
                <color>#FF6666</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/GW_CTRL_EngagementDashboard.cls
public with sharing class GW_CTRL_EngagementDashboard {


	// public list<sobject> aggResults {get;set;}
	public list<aggEngagementRow> rows {get;set;}

	// constructor
	public GW_CTRL_EngagementDashboard () {
		this.rows = new list<aggEngagementRow>();
		queryEngagementCounts();
		
	}
	
	
	public void queryEngagementCounts () {
		
		list<sObject> results;
		
		results = [Select Engagement_Level__c Level, COUNT_DISTINCT(Id) TotalCount 
			FROM Contact WHERE Engagement_Level_Numeric__c > 0 
			GROUP BY Engagement_Level__c];
			
		// aggResults = results;
		
		for (sobject result:results) {
			aggEngagementRow row = new aggEngagementRow();
			row.levelName = (string) result.get('Level');
			row.countCons = (integer) result.get('TotalCount');
			rows.add(row);
		}
		
	}
	
	
	//wrapper class
	public class aggEngagementRow {
		
		public string levelName {get;set;}
		public integer countCons {get;set;} 
		
	}
	

}