src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <inlineHelpText>campaign id that is passed from Plone form</inlineHelpText>
        <label>Campaign Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Status__c</fullName>
        <inlineHelpText>Used during the import process, this allows you to set member status for leads on a campaign.</inlineHelpText>
        <label>Campaign Member Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_City__c</fullName>
        <inlineHelpText>Home City</inlineHelpText>
        <label>Home City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_PostalCode__c</fullName>
        <inlineHelpText>Home Zip/Postal Code</inlineHelpText>
        <label>Home Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_State__c</fullName>
        <inlineHelpText>Home State</inlineHelpText>
        <label>Home State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Street__c</fullName>
        <inlineHelpText>Home street address</inlineHelpText>
        <label>Home Street</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/classes/ONEN_CTRL_WebToLead.cls
public class ONEN_CTRL_WebToLead {
// Written by Dave Manelski, copyright (c) 2010 Groundwire
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

	public Lead lead { 
		get {
			if (lead == null) lead = new Lead();
			return lead;
		}
		
		set; 
	}
	
	public PageReference Save() {
		if (lead.Company == null) lead.Company = '[not provided]'; 
		insert lead;
		StrSaveResult = 'Your information has been saved.  Thank you.';
		lead = null;	// so fields get reset to null.
		return null;
	}
	
	public String StrSaveResult { get; set; }
	
	public PageReference insertLead() {
		Map<string,string> postParameters = ApexPages.currentPage().getParameters();
		
		if (!postParameters.isEmpty()) {
			Lead newLead = new Lead();
			newLead.FirstName = ApexPages.currentPage().getParameters().get('First_Name');
			
			//hard code [not provided] for people without last names or company
			if (ApexPages.currentPage().getParameters().get('Last_Name')==null || ApexPages.currentPage().getParameters().get('Last_Name')=='') {
				newLead.LastName = '[not provided]';
			} else {
				newLead.LastName = ApexPages.currentPage().getParameters().get('Last_Name');
			}
			
			if (ApexPages.currentPage().getParameters().get('Organization')==null || ApexPages.currentPage().getParameters().get('Organization')=='') {
				newLead.LastName = '[not provided]';
			} else {
				newLead.Company = ApexPages.currentPage().getParameters().get('Organization');
			}
	
			newLead.Email = ApexPages.currentPage().getParameters().get('Email');
			newLead.Home_Phone__c = ApexPages.currentPage().getParameters().get('Home_Phone');
			newLead.MobilePhone = ApexPages.currentPage().getParameters().get('Mobile');
			newLead.LeadSource = ApexPages.currentPage().getParameters().get('Lead_Source');
			if (ApexPages.currentPage().getParameters().get('Email_Opt_Out') != null) {
				newLead.HasOptedOutOfEmail = ApexPages.currentPage().getParameters().get('Email_Opt_Out').contains('true');
			}
			newLead.Campaign_Id__c = ApexPages.currentPage().getParameters().get('Campaign_Id');
			newLead.Campaign_Member_Status__c = ApexPages.currentPage().getParameters().get('Campaign_Member_Status');
			newLead.Home_Street__c = ApexPages.currentPage().getParameters().get('Home_Street');
			newLead.Home_City__c = ApexPages.currentPage().getParameters().get('Home_City');
			newLead.Home_State__c = ApexPages.currentPage().getParameters().get('Home_State');
			newLead.Home_PostalCode__c = ApexPages.currentPage().getParameters().get('Home_PostalCode');
			
			insert newLead;
		}
		
		return null;
	}
	
	//==================== TEST METHOD(s) ======================================
	static testmethod void CodeCoverageTests() {

		PageReference pageRef=Page.webtolead; 
		Test.setCurrentPage(pageRef); 

		// set the parameter for the contact
		ApexPages.currentPage().getParameters().put('Last_Name', 'Chekov');

		//instantiate the controller 
		ONEN_CTRL_WebToLead ctrl = new ONEN_CTRL_WebToLead();

		ctrl.insertlead();
		
		Lead lead = ctrl.lead;
		System.Assert(lead != null);
		lead.FirstName = 'TestFirstName';
		lead.LastName = 'TestLastName';
		ctrl.Save();
		System.AssertEquals('Your information has been saved.  Thank you.', ctrl.StrSaveResult);
	}	
}