src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CR_Contact_Id__c</fullName>
        <inlineHelpText>Field used by code that creates new opportunities</inlineHelpText>
        <label>CR Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CR_Contact_Role__c</fullName>
        <inlineHelpText>Field used by code that creates new opportunities</inlineHelpText>
        <label>CR Contact Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OppPayment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Installment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsInstallment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Installment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opp_For_Installment__c</fullName>
        <inlineHelpText>The Opportunity this is an installment for.  If null, then this is a mirror payment for its master opportunity.</inlineHelpText>
        <label>Opp For Installment</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Payments_Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Written_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Written Off</label>
        <type>Checkbox</type>
    </fields>
    <label>Opp Installment</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Installment Nbr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Installments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ONEN_EXT_MarkPaymentsPaid.cls
public with sharing class ONEN_EXT_MarkPaymentsPaid {
// Written by Dave Manelski, copyright (c) 2009 ONE/Northwest
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

    private List<OppPayment__c> selectedInstallments;
    private String mark;    
    
    //have to instantiate with StandardSetController for list buttons
    public ONEN_EXT_MarkPaymentsPaid(ApexPages.StandardSetController controller) {
        //get the selected ids that were checked
        this.selectedInstallments = (List<OppPayment__c>)controller.getSelected();
        //thisYear = string.valueOf(system.Today().Year());
        // mark = ApexPages.currentPage().getParameters().get('mark');
    }
    
    public pageReference markInstallmentsPaid() {
        mark='paid';
        PageReference p = markInstallments();
        return p;
    }
    
    public pageReference markInstallmentsWrittenOff() {
        mark='writeoff';
        PageReference p = markInstallments();
        return p;
    }
    
    pageReference markInstallments() {
        //get all the installments that were selected
        List<OppPayment__c> InstallmentsFromSelection = [select Id,paid__c from OppPayment__c where Id IN :selectedInstallments];
        if (InstallmentsFromSelection.size()>0) {
            for (OppPayment__c thisInstallment : InstallmentsFromSelection) {
                //if we're passing in paid on the querystring, mark them paid
                if(mark=='paid') {
                    thisInstallment.paid__c=true;
                    thisInstallment.Written_Off__c=false;
                } else if(mark=='writeoff') {
                    thisInstallment.Written_Off__c=true;
                    thisInstallment.paid__c=false;                  
                }
            }
                
            update InstallmentsFromSelection;
        }
        PageReference p = new PageReference(System.currentPageReference().getParameters().get('retURL'));
        p.setRedirect(true);
        return p;
        
    }

    /* TESTS */

    private static testMethod void TestMarkAsPaid() {
    
    //create first contact
      Contact firstContact = new Contact (
      FirstName='Joe',
      LastName='Schmoe_for_tests'
      );
      insert firstContact;
    
    //new opp for contact
    Opportunity firstOpp = new Opportunity (
        RecordTypeId = GW_RecTypes.GetRecordTypeId('Opportunity', ONEN_Constants.OPP_DEFAULT_RECTYPE_FORTESTS), 
        Name = 'Test first contact opp',
        amount=100,
        StageName=ONEN_Constants.OPP_DEFAULT_STAGE,
        CloseDate=Date.newInstance(2005,10,10),
        CR_Contact_Id__c = firstContact.id,
        CR_Contact_Role__c = ONEN_Constants.OPP_GIFT_DONOR_ROLE(ONEN_Constants.OPP_DEFAULT_RECTYPE_FORTESTS)
    );
    
    insert firstOpp;
    
    OppPayment__c firstPayment = new OppPayment__c (
        Opportunity__c = firstOpp.id,
        Opp_For_Installment__c = firstOpp.id,
        IsInstallment__c = true,
        paid__c=false,
        Date__c = Date.newInstance(2005,10,10),
        Amount__c = 10
    );
    
    insert firstPayment;
    
    List<OppPayment__c> selectedInstallments = new List<OppPayment__c>();
    
    selectedInstallments.add(firstPayment);
    
    PageReference p = new PageReference('/' + firstContact.id + '?retURL=' + firstContact.id);
    Test.setCurrentPage(p);
    
    //pass selected opportunities into the controller
    ApexPages.StandardSetController sc = new ApexPages.standardSetController(selectedInstallments);
    sc.setSelected(selectedInstallments);
    ApexPages.currentPage().getParameters().put('mark', 'paid');
    //pass the controller into the extension
    ONEN_EXT_MarkPaymentsPaid ext = new ONEN_EXT_MarkPaymentsPaid(sc);
    
    ext.markInstallmentsPaid();
    
    OppPayment__c[] payments = [SELECT id, paid__c FROM OppPayment__c where id = :firstPayment.id ];
    system.assertEquals(1,payments.size());
    System.assertEquals(true,payments[0].paid__c);
    
    }
        
    private static testMethod void TestMarkWriteOff() {
    
    //create first contact
      Contact firstContact = new Contact (
      FirstName='Joe',
      LastName='Schmoe_for_tests'
      );
      insert firstContact;
    
    //new opp for contact
    Opportunity firstOpp = new Opportunity (
        RecordTypeId = GW_RecTypes.GetRecordTypeId('Opportunity', ONEN_Constants.OPP_DEFAULT_RECTYPE_FORTESTS), 
        Name = 'Test first contact opp',
        amount=100,
        StageName=ONEN_Constants.OPP_DEFAULT_STAGE,
        CloseDate=Date.newInstance(2005,10,10),
        CR_Contact_Id__c = firstContact.id,
        CR_Contact_Role__c = ONEN_Constants.OPP_GIFT_DONOR_ROLE(ONEN_Constants.OPP_DEFAULT_RECTYPE_FORTESTS)
    );
    
    insert firstOpp;
    
    OppPayment__c firstPayment = new OppPayment__c (
        Opportunity__c = firstOpp.id,
        Opp_For_Installment__c = firstOpp.id,
        IsInstallment__c = true,
        paid__c=false,
        Date__c = Date.newInstance(2005,10,10),
        Amount__c = 10
    );
    
    insert firstPayment;
    
    List<OppPayment__c> selectedInstallments = new List<OppPayment__c>();
    
    selectedInstallments.add(firstPayment);
    
    PageReference p = new PageReference('/' + firstContact.id + '?retURL=' + firstContact.id);
    Test.setCurrentPage(p);
    
    //pass selected opportunities into the controller
    ApexPages.StandardSetController sc = new ApexPages.standardSetController(selectedInstallments);
    sc.setSelected(selectedInstallments);
    // ApexPages.currentPage().getParameters().put('mark', 'writeoff');
    //pass the controller into the extension
    ONEN_EXT_MarkPaymentsPaid ext = new ONEN_EXT_MarkPaymentsPaid(sc);
    
    ext.markInstallmentsWrittenOff();
    
    OppPayment__c[] payments = [SELECT id, written_off__c FROM OppPayment__c where id = :firstPayment.id ];
    system.assertEquals(1,payments.size());
    System.assertEquals(true,payments[0].written_off__c );
    
    }

}